# tasks file for redis
---
- name: update
  hosts: all
  gather_facts: false
  become: yes  
  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Installing Redis
      apt: name=redis-server state=latest

     # notify:
      #  - restart redis.service

    - name: Restart Redis Server
      service: name=redis state=restarted enabled=yes
